### ISSUE TITLE
Profaned Guardians are not summoned

### ISSUE THREAD

**Issue by b1of** [InfernumTeam/InfernumModePublic#129]
In a Profaned garden it is impossible to read the tablet and summon Profaned guardians

https://github.com/DominicKarma/InfernumModePublic/assets/107925877/1f09ebef-3e07-493a-9ad6-b1cd9e734381

[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12721699/client.log)

**Comment by frugbub** [comment]
Same thing happening to me i have no idea how to fix

**Comment by Jatie1** [comment]
There is a new debug item called Profaned Garden Location Setter, you can use it to fix the profaned garden

**Comment by Eeeeke** [comment]
I'm playing with my friends on a multiplayer world and nothing worked. Using Profaned Garden Location Setter just removed the creative shock de buff so we could break everything (I used the garden location setter exactly where the description said I should)

**Comment by toasty599** [comment]
> I'm playing with my friends on a multiplayer world and nothing worked. Using Profaned Garden Location Setter just removed the creative shock de buff so we could break everything (I used the garden location setter exactly where the description said I should)

you must use it in singleplayer.
