### ISSUE TITLE
There is a bug in the supreme disaster

### ISSUE THREAD

**Issue by tcsccw** [InfernumTeam/InfernumModePublic#140]
1.When the mode is turned on, there will be problems in the ultimate disaster, and the end stage will collapse.When the mode is turned on, there will be problems in the ultimate disaster, and the end stage will collapse.
2.Every time the supreme disaster says "... congratulations." The game will crash, and then there will be a prompt that the host crashed
![微信图片_20240101220116](https://github.com/InfernumTeam/InfernumModePublic/assets/155370673/ec495cd3-886c-49b5-875f-ed705f3756a3)
![微信图片_20240101220307](https://github.com/InfernumTeam/InfernumModePublic/assets/155370673/d86a14ff-4f2c-4139-a683-f1991fd50785)
[client.log](https://github.com/InfernumTeam/InfernumModePublic/files/13804752/client.log)

**Comment by anonymous000000** [comment]
tModLoader 1.4.3 is not supported, update to 1.4.4 or kill her in Death Mode to progress

**Comment by Godslayer40000** [comment]
actually i would highly recommend just upgrading, 1.4.3 is really buggy when it comes to mods as it was tmodloaders first dip into 1.4
