### ISSUE TITLE
Bosses didn`t die 

### ISSUE THREAD

**Issue by en1ername** [InfernumTeam/InfernumModePublic#145]
In infernum some bosses didn`t die. Bosses that i checked are Twins, King of Slimes. I don't know if others have this problem.
https://youtu.be/Z--cmaVElDA

My list of mods:
Potion Fountains
Improved Movement Visuals
Radiance
Hunt of the Old God
Infernum (and req)
Weapon Enchantments
Koko Net Lib
androLib
Vacuum Ore Bag
Subworld Library
Boss Checklist
AlchemistNPC Lite
Magic Storage
absoluteAquarian Utilities
Boss Cursor
Quality of Terraria
Wing Slot Extra
Recipe Browser
Catalyst Mod
Max Stack Plus Extra
Which Mod Is This From? (WMITF)
Auto Reforge
Better Boss Health Bar for 1.4.4+
Cheat Sheet
Colored Calamity Relics
Project tRU
Infernum Mode Music
More Accessory Slots
Calamity Mod Extra Music
Friendly NPCs Don't Die
Terraria Overhaul
Shoe Slot
Boss Intros
Better Expert Rarity
Better Game UI
Calamity's Vanities
Calamity Rarities
Loot Beams
Lights And Shadow
MEAC
Better Russian Font
Optimized Cursor
Better Blending
Wing Time UI
HP Awareness
Summoner UI
Colored Damage Types
HERO's Mod
Cheat Extensions for Hero's/Cheat Sheet
No Pylon Restrictions
LuiAFK Reborn

**Comment by toasty599** [comment]
With this many mods, this is not an Infernum issue. Find the offending mod and disable it.

**Comment by en1ername** [comment]
Ok thank you. Maybe some mods broke some bosses.
