### ISSUE TITLE
Calamity Boss Health Multiplier not working on Infernum

### ISSUE THREAD

**Issue by jclifz** [InfernumTeam/InfernumModePublic#153]
I'm not sure if it is a Tmodloader issue or an Infernum mod issue, but from what I've been testing I've gotten rid of all mods besides calamity mods and the cheat sheet mod to see the booster's effects on the bosses. So far every other calamity mode allows the health booster to work but once the difficulty is changed to Infernum the effects aren't apparent. This was first tested in singleplayer and next multiplayer, both don't receive booster effects. I would like to know if this same issue is found on other computers. My last resort will be deleting all files of the mod loader, running it fresh, and seeing the effects of the booster but before then I would like to see if this is an issue only belonging to me.

**Comment by toasty599** [comment]
This is a calamity issue, they do not apply the HP scaling properly. Bring it up with them.

**Comment by jclifz** [comment]
thankyou
